### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by felixmosh** [tinymce/tinymce-react#243]
**What is the current behavior?**
when updating to v3.12.0 on my Next.js app, it throws an error during production build.

```
> Build error occurred
ReferenceError: window is not defined
    at Object.isBeforeInputEventAvailable (/Users/***/Projects/node/***/node_modules/@tinymce/tinymce-react/lib/cjs/main/ts/Utils.js:61:49)
    at Object.<anonymous> (/Users/***/Projects/node/***/node_modules/@tinymce/tinymce-react/lib/cjs/main/ts/components/Editor.js:43:32)
    at Module._compile (internal/modules/cjs/loader.js:1236:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1257:10)
    at Module.load (internal/modules/cjs/loader.js:1085:32)
    at Function.Module._load (internal/modules/cjs/loader.js:950:14)
    at Module.require (internal/modules/cjs/loader.js:1125:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/Users/***/Projects/node/***/node_modules/@tinymce/tinymce-react/lib/cjs/main/ts/index.js:11:16)
    at Module._compile (internal/modules/cjs/loader.js:1236:30) {
  type: 'ReferenceError'
}
```
**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io]
Create a next.js app with a page with TinyMCE, run `yarn build`

**What is the expected behavior?**
It should not throw this exception during build.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**
It throws on `v3.12.0` and it worked on `v3.10.4`

**Comment by tiny-james** [comment]
Sorry I did not consider server side rendering. I will investigate.

**Comment by tiny-james** [comment]
Release 3.12.1 is now available and should fix this issue.

**Comment by felixmosh** [comment]
Thank you for the quick fix 🙏🏼
I've tested it, it works
